### ISSUE TITLE
[1.20.1] Mixin failed on server startup

### ISSUE THREAD

**Issue by FoxMcloud5655** [KaboomRoads/LostFeatures#6]
I haven't tested with a smaller modpack, but I'm encountering this error on version 0.7.2.2:
```
Mixin apply failed lostfeatures.mixins.json:ClientLevelMixin -> net.minecraft.client.multiplayer.ClientLevel: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyExpressionValue annotation on modifyCanSpawn could not find any targets matching 'lambda$doAnimateTick$8' in net.minecraft.client.multiplayer.ClientLevel. Using refmap lostfeatures.refmap.json [PREINJECT Applicator Phase -> lostfeatures.mixins.json:ClientLevelMixin -> Prepare Injections ->  -> modifyExpressionValue$dgp000$modifyCanSpawn(ZLnet/minecraft/core/BlockPos$MutableBlockPos;Lnet/minecraft/world/level/biome/AmbientParticleSettings;)Z -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyExpressionValue annotation on modifyCanSpawn could not find any targets matching 'lambda$doAnimateTick$8' in net.minecraft.client.multiplayer.ClientLevel. Using refmap lostfeatures.refmap.json [PREINJECT Applicator Phase -> lostfeatures.mixins.json:ClientLevelMixin -> Prepare Injections ->  -> modifyExpressionValue$dgp000$modifyCanSpawn(ZLnet/minecraft/core/BlockPos$MutableBlockPos;Lnet/minecraft/world/level/biome/AmbientParticleSettings;)Z -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at com.llamalad7.mixinextras.injector.MixinExtrasInjectionInfo.<init>(MixinExtrasInjectionInfo.java:10) ~[MixinExtras-0.2.0-rc.3.jar%23788!/:?]
	at com.llamalad7.mixinextras.injector.ModifyExpressionValueInjectionInfo.<init>(ModifyExpressionValueInjectionInfo.java:14) ~[MixinExtras-0.2.0-rc.3.jar%23788!/:?]
```
This error doesn't appear in version 0.7.2.1 of the mod.

**Comment by KaboomRoads** [comment]
I was not able to reproduce the issue, but I have slightly changed the problematic mixin in 0.7.2.2.1 to make it work like it did before while remaining compatible with other mods.

**Comment by FoxMcloud5655** [comment]
I will attempt this new version and report back.  Thanks for the quick update!

**Comment by FoxMcloud5655** [comment]
I can confirm that this fixes the issue in multiple modpack setups.
